name: build CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    ## checkout후 자바 17 버전으로 설정을 합니다
    runs-on: ubuntu-latest
    steps:
      # workflow가 repository를 접근할 수 있게 checkout
      - uses: actions/checkout@v3

      # java 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # application.yml 환경변수 적용
      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.datasource.url: ${{ secrets.DB_HOST }}
          spring.datasource.username: ${{ secrets.DB_USER }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      # gradle을 이용한 java 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
